---
<<<<<<< HEAD
- name : installation nginx test12
=======
- name : installation nginx test11
>>>>>>> aa131e27a4f91af769fd4c993389aa1f3cf5e4ca
  hosts: all
  tasks : 
    - name : update yum
      yum : 
        update_cache : yes

    - name : ajout depot EPEL
      yum : 
        name : epel-release
        state : present
  
    - name : update yum
      yum : 
        update_cache : yes

    - name : remove httpd
      yum: 
        name : "httpd"
        state: removed

    - name : installation nginx
      yum:
        name: nginx
        state: present

    - name: start nginx
      service: 
        name: nginx
        state: start
        enabled: yes


...

